server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_4_db
    username: db_user
    password: db_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false


logging:
  level:
    com.example.jwt.exception: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql: WARN
    org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator: WARN

jwt4:
  app:
    accessSecret: m9QJxZx2v8mK4y9A8n0VZzK5kC4f5pQFJ8sZ3Yy1cKkX9x5K0pVZyQZzZyKZ1mF6A7bN3cP2dQ8eR5fT9gU4hV1iW6jX
    refreshSecret: 8DQJxZx2v8mK4y9A8n0VZzK5kC4f5pQFJ8sZ3Yy1cKkX9x5K0pVZyQZzZyKZ1mF6A7bN3cP2dQ8eR5fT9gU4hV1iWkLm
    jwtExpirationMs: 900000          # 15 dk
    refreshExpirationMs: 604800000   # 7 g√ºn
